# config.py — auto-generated by discover_vault.py, do not edit manually
# Edit .env for API keys; re-run discover_vault.py to update paths

from pathlib import Path
from dotenv import load_dotenv
import os

_PROJECT_ROOT = Path(__file__).parent.parent
load_dotenv(_PROJECT_ROOT / ".env")

# Vault paths — populated by discover_vault.py
VAULT_PATH = Path(os.environ["VAULT_PATH"])
INBOX_PATH = Path(os.environ["INBOX_PATH"])
DAILY_PATH = Path(os.environ.get("DAILY_PATH", "")) if os.environ.get("DAILY_PATH") else None
MOCS_PATH = Path(os.environ.get("MOCS_PATH", "")) if os.environ.get("MOCS_PATH") else None
OUTPUT_PATH = Path(os.environ.get("OUTPUT_PATH", "")) if os.environ.get("OUTPUT_PATH") else None
TAGGING_NOTE_PATH = Path(os.environ["TAGGING_NOTE_PATH"]) if os.environ.get("TAGGING_NOTE_PATH") else None

# Detected frontmatter conventions
DATE_FORMAT = os.environ.get("DATE_FORMAT", "%Y-%m-%d")
TAG_FORMAT = os.environ.get("TAG_FORMAT", "list")  # "list" or "inline"
FRONTMATTER_FIELDS = os.environ.get("FRONTMATTER_FIELDS", "title,source,tags,created").split(",")

# API
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
CLAUDE_MODEL_HEAVY = os.environ.get("CLAUDE_MODEL_HEAVY", "claude-opus-4-6")
CLAUDE_MODEL_LIGHT = os.environ.get("CLAUDE_MODEL_LIGHT", "claude-haiku-4-5-20251001")
CLAUDE_MAX_TOKENS = int(os.environ.get("CLAUDE_MAX_TOKENS", "4096"))

# Jina
JINA_BASE_URL = "https://r.jina.ai"

# Scripts
SCRIPTS_PATH = Path(__file__).parent
PROJECT_ROOT = SCRIPTS_PATH.parent
PROMPTS_PATH = SCRIPTS_PATH / "prompts"
